version: "3.7"

services:
  copier:
    build: ../docker #TODO remove this since it is path specific, use :dev image, once i know how
    environment:
      FOLDER_PAIRS: "some_sda_folder:all_sda;some_other_sda_folder:all_sda;nested/first:first;nested/second:second"
      SOURCE_ROOT: "/opt/src/"
      TARGET_ROOT: "/opt/target/"
    volumes:
      - ./../playground/sandbox/src:/opt/src
      - ./../playground/sandbox/target:/opt/target