version: "3.9"

services:
  copier:
    build: ../docker
    environment:
      SCRIPT_FILE_PATH: "/replacements.sed" # this is also the default value, to use a custom script mount it as volume and change this path
      SOURCE_ROOT: "/mnt/src/"
      TARGET_ROOT: "/mnt/target/"
      # The "root" environment variables should end with a '/'
    volumes:
      - ./replacements.sed:/replacements.sed
      - ./volumes/src:/mnt/src
      - ./volumes/target:/mnt/target