version: "3.9"

services:
  copier:
    build: ../docker
    environment:
      SCRIPT_FILE_PATH: "/replacements.sed" # this is also the default value
      SOURCE_ROOT: "/opt/src/"
      TARGET_ROOT: "/opt/target/"
      # The "root" environment variables should end with a '/'
    volumes:
      - ./../sandbox/src:/opt/src
      - ./../sandbox/target:/opt/target