version: "3.7"

services:
  copier:
    build: ../docker
    environment:
      FOLDER_PAIRS: |
        ^my_dir/#other_dir/
        ^spacey dir/#not_so_spacey/
        ^not_so_spacey/#spacey target/
        ^my_other_dir/#other_dir/
        nested/first/#first/
        nested/second/#second/
      # mappings cant have line ending marker
      # The "root" environment variables should end with a '/'
      SOURCE_ROOT: "/opt/src/"
      TARGET_ROOT: "/opt/target/"
    volumes:
      - ./../sandbox/src:/opt/src
      - ./../sandbox/target:/opt/target