version: "3.9"

services:
  copier:
    build: ../docker
    environment: &copy-env
      SCRIPT_FILE_PATH: "/replacements.sed" # this is also the default value, to use a custom script mount it as volume and change this path
      SOURCE_ROOT: "/mnt/src/"
      TARGET_ROOT: "/mnt/target/"
      # IMPORTANT: The "root" environment variables should end with a '/'
    volumes:
      - ./replacements.sed:/replacements.sed
      - ./volumes/src:/mnt/src:ro
      - ./volumes/target:/mnt/target

  copier-sha:
    build: ../docker
    environment:
      <<: *copy-env
      APPEND_SHA1_SUM: "true"
    volumes:
      - ./volumes/src:/mnt/src:ro
      - ./volumes/target:/mnt/target
      - ./replacements-sha.sed:/replacements.sed

  copier-delete:
    build: ../docker
    environment:
      <<: *copy-env
      # ATTENTION: Requires write permissions on the source volume
      DELETE_SOURCE_FILE: "true"
    volumes:
      - ./volumes/src:/mnt/src
      - ./volumes/target:/mnt/target
      - ./replacements-delete.sed:/replacements.sed
